export const skills = {
  frontend: [
    { name: "React.js", level: 95 },
    { name: "Next.js", level: 90 },
    { name: "TypeScript", level: 85 },
    { name: "Vue.js", level: 75 },
    { name: "TailwindCSS", level: 95 },
    { name: "Bootstrap", level: 90 },
    { name: "HTML5 / CSS3", level: 95 },
    { name: "Responsive Design", level: 92 },
  ],
  backend: [
    { name: "Node.js", level: 90 },
    { name: "C# / .NET Core", level: 88 },
    { name: "REST API", level: 92 },
    { name: "MVC Architecture", level: 85 },
    { name: "Service-Repository", level: 83 },
    { name: "Express.js", level: 85 },
  ],
  database: [
    { name: "PostgreSQL", level: 82 },
    { name: "MySQL", level: 88 },
    { name: "MSSQL", level: 85 },
    { name: "MongoDB", level: 80 },
  ],
  devops: [
    { name: "Git / GitHub", level: 92 },
    { name: "React Query", level: 85 },
    { name: "Axios", level: 90 },
    { name: "Docker (Temel)", level: 65 },
    { name: "Vercel / Hosting", level: 88 },
  ],
  gamedev: [
    { name: "Unity 2D/3D", level: 80 },
    { name: "C# (Unity)", level: 85 },
    { name: "FiveM Scripts", level: 78 },
    { name: "Rust Server Scripts", level: 75 },
  ],
  it: [
    { name: "PC Assembly", level: 92 },
    { name: "Network Management", level: 80 },
    { name: "Windows Optimization", level: 88 },
    { name: "Server / Hosting", level: 82 },
    { name: "Cyber Security", level: 72 },
  ],
};

export const projects = [
  {
    id: 1,
    slug: "vitisfera-crm",
    category: "crm",
    featured: true,
    gradient: "from-cyan-500/20 via-blue-500/20 to-purple-500/20",
    titleTr: "Vitisfera CRM Yönetim Paneli",
    titleEn: "Vitisfera CRM Admin Panel",
    categoryLabelTr: "CRM Sistemi",
    categoryLabelEn: "CRM System",
    descTr:
      "Satış ekiplerinin sahadaki aktivitelerini anlık takip eden, aylık hedefleri ve prim sistemini otomatik hesaplayan, yapay zeka destekli kurumsal yönetim paneli.",
    descEn:
      "AI-powered enterprise management panel that tracks sales team field activities in real-time, automatically calculates monthly targets and commission systems.",
    techs: ["React", "TypeScript", "TailwindCSS", "Node.js", "MongoDB", "AI Integration"],
    github: null,
    live: null,
  },
  {
    id: 2,
    slug: "lawyer-saas",
    category: "saas",
    featured: true,
    gradient: "from-purple-500/20 via-pink-500/20 to-rose-500/20",
    titleTr: "Avukat & Hukuk Bürosu Yönetim Sistemi",
    titleEn: "Law Firm Management System",
    categoryLabelTr: "SaaS Çözümü",
    categoryLabelEn: "SaaS Solution",
    descTr:
      "Müvekkil takibi, dava dosyalarının dijital yönetimi ve duruşma takvimi entegrasyonu sağlayan kapsamlı SaaS çözümü.",
    descEn:
      "Comprehensive SaaS solution providing client tracking, digital case file management, and hearing schedule integration for law firms.",
    techs: ["React", "TypeScript", "TailwindCSS", "REST API"],
    github: null,
    live: null,
  },
  {
    id: 3,
    slug: "unity-survival",
    category: "game",
    featured: true,
    gradient: "from-green-500/20 via-teal-500/20 to-cyan-500/20",
    titleTr: "Unity 2D Survival Oyunu",
    titleEn: "Unity 2D Survival Game",
    categoryLabelTr: "Oyun Geliştirme",
    categoryLabelEn: "Game Development",
    descTr:
      "Karmaşık AI sistemleri, prosedürel dünya oluşturma, çok oyunculu ağ ve mobil platformlar için optimize edilmiş performans içeren gelişmiş 2D survival oyunu.",
    descEn:
      "Advanced 2D survival game featuring complex AI systems, procedural world generation, multiplayer networking, and performance optimized for mobile platforms.",
    techs: ["Unity", "C#", "2D Graphics", "Physics Systems", "Multiplayer", "Mobile"],
    github: null,
    live: null,
  },
  {
    id: 4,
    slug: "perfgame",
    category: "saas",
    featured: false,
    gradient: "from-orange-500/20 via-yellow-500/20 to-amber-500/20",
    titleTr: "PerfGame - PC Optimizasyon Uygulaması",
    titleEn: "PerfGame - PC Optimization App",
    categoryLabelTr: "Masaüstü Uygulama",
    categoryLabelEn: "Desktop Application",
    descTr:
      "Bilgisayar ve oyun performansını artırmaya yönelik geliştirdiğim masaüstü optimizasyon uygulaması. Otomatik sistem ayarları ve performans analizi.",
    descEn:
      "Desktop optimization application designed to improve computer and gaming performance. Automated system settings and performance analytics.",
    techs: ["C#", ".NET", "Windows API", "Performance Analysis"],
    github: null,
    live: null,
  },
  {
    id: 5,
    slug: "game-web-scripts",
    category: "web",
    featured: false,
    gradient: "from-red-500/20 via-orange-500/20 to-yellow-500/20",
    titleTr: "Oyun Sunucu Web Entegrasyonları",
    titleEn: "Game Server Web Integrations",
    categoryLabelTr: "Oyun Web",
    categoryLabelEn: "Game Web",
    descTr:
      "Rust ve FiveM gibi oyun sunucuları için oyuncu istatistikleri, market entegrasyonu ve yönetim paneli içeren web siteleri.",
    descEn:
      "Web platforms for game servers like Rust and FiveM, featuring player statistics, market integration, and admin panels.",
    techs: ["Node.js", "React", "MySQL", "WebSocket", "REST API"],
    github: null,
    live: null,
  },
  {
    id: 6,
    slug: "ecommerce-scripts",
    category: "web",
    featured: false,
    gradient: "from-indigo-500/20 via-blue-500/20 to-cyan-500/20",
    titleTr: "E-Ticaret Altyapısı & Scriptleri",
    titleEn: "E-Commerce Infrastructure & Scripts",
    categoryLabelTr: "E-Ticaret",
    categoryLabelEn: "E-Commerce",
    descTr:
      "İşletmeler için özel kodlanmış, yüksek performanslı e-ticaret altyapıları ve SaaS tabanlı mağaza yönetim scriptleri.",
    descEn:
      "Custom-coded, high-performance e-commerce infrastructure and SaaS-based store management scripts for businesses.",
    techs: ["React", "Node.js", "PostgreSQL", "Stripe API", "Redis"],
    github: null,
    live: null,
  },
];

export const experiences = [
  {
    id: 1,
    type: "work",
    startDateTr: "2023",
    startDateEn: "2023",
    endDateTr: "Devam",
    endDateEn: "Present",
    roleTr: "Freelance Full Stack Geliştirici",
    roleEn: "Freelance Full Stack Developer",
    companyTr: "Serbest Çalışan — Bionluk & Özel Müşteriler",
    companyEn: "Self-Employed — Bionluk & Private Clients",
    locationTr: "Ankara, Türkiye (Remote)",
    locationEn: "Ankara, Turkey (Remote)",
    descriptionTr: [
      "KOBİ ve kurumsal müşteriler için kurumsal web siteleri, landing page'ler ve tanıtım siteleri geliştirdim.",
      "CRM tabanlı yönetim panelleri, satış takip sistemleri ve raporlama araçları oluşturdum.",
      "Avukatlık bürosu, inşaat firması, güzellik merkezi gibi farklı sektörlere özel SaaS çözümler ürettim.",
      "Müşteri memnuniyetini %100 koruyarak 25+ projeyi başarıyla teslim ettim.",
    ],
    descriptionEn: [
      "Built corporate websites, landing pages, and showcase sites for SMBs and enterprise clients.",
      "Created CRM-based admin panels, sales tracking systems, and reporting tools.",
      "Delivered sector-specific SaaS solutions for law firms, construction companies, beauty centers, and more.",
      "Successfully delivered 25+ projects with 100% client satisfaction.",
    ],
    techs: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "TailwindCSS"],
  },
  {
    id: 2,
    type: "work",
    startDateTr: "2021",
    startDateEn: "2021",
    endDateTr: "2023",
    endDateEn: "2023",
    roleTr: "Freelance Web & Oyun Script Geliştirici",
    roleEn: "Freelance Web & Game Script Developer",
    companyTr: "Serbest Çalışan — Bionluk Platformu",
    companyEn: "Self-Employed — Bionluk Platform",
    locationTr: "Remote",
    locationEn: "Remote",
    descriptionTr: [
      "Bionluk üzerinden 50+ müşteriye web geliştirme ve script yazımı hizmeti verdim.",
      "Rust, FiveM ve Minecraft sunucuları için oyuncu istatistikleri, market ve yönetim paneli scriptleri yazdım.",
      "E-ticaret altyapıları, ödeme entegrasyonları ve mağaza yönetim sistemleri geliştirdim.",
      "Güvenlik açıklarını kapatmaya yönelik siber güvenlik çalışmaları yürüttüm.",
    ],
    descriptionEn: [
      "Provided web development and scripting services to 50+ clients via Bionluk platform.",
      "Wrote player statistics, marketplace, and admin panel scripts for Rust, FiveM, and Minecraft servers.",
      "Developed e-commerce infrastructures, payment integrations, and store management systems.",
      "Conducted cybersecurity work to identify and close vulnerabilities.",
    ],
    techs: ["Node.js", "PHP", "MySQL", "JavaScript", "C#", "Unity"],
  },
  {
    id: 3,
    type: "education",
    startDateTr: "2025",
    startDateEn: "2025",
    endDateTr: "Devam",
    endDateEn: "Present",
    roleTr: "Önlisans — Web Tasarımı ve Kodlama",
    roleEn: "Associate's Degree — Web Design & Coding",
    companyTr: "Ankara Üniversitesi",
    companyEn: "Ankara University",
    locationTr: "Ankara, Türkiye",
    locationEn: "Ankara, Turkey",
    descriptionTr: [
      "Web teknolojileri, veritabanı yönetimi ve modern yazılım geliştirme standartları üzerine eğitime devam ediyorum.",
    ],
    descriptionEn: [
      "Continuing education focused on web technologies, database management, and modern software development standards.",
    ],
    techs: ["Web Technologies", "Database Management", "Software Engineering"],
  },
];

export const stats = [
  { value: 5, suffix: "+", keyTr: "Yıl Deneyim", keyEn: "Years Experience" },
  { value: 100, suffix: "+", keyTr: "Tamamlanan Proje", keyEn: "Projects Completed" },
  { value: 15, suffix: "+", keyTr: "Teknoloji", keyEn: "Technologies" },
  { value: 99, suffix: "%", keyTr: "Müşteri Memnuniyeti", keyEn: "Client Satisfaction" },
];

export const social = {
  email: "tufanege123@gmail.com",
  github: "https://github.com/xRevenge06",
  discord: "revenge06",
  bionluk: "https://bionluk.com/revtufan",
  linkedin: "https://linkedin.com/in/tufan-kiraz-920580387",
};
