export const skillGroups = {
  frontend: [
    "React.js",
    "Next.js",
    "TypeScript",
    "Vue.js",
    "Tailwind CSS",
    "Responsive Design",
    "HTML5 / CSS3",
  ],
  backend: [
    "Node.js",
    "C# / .NET Core",
    "REST API",
    "Express.js",
    "MVC Architecture",
    "Service-Repository Pattern",
  ],
  database: [
    "PostgreSQL",
    "MySQL",
    "MSSQL",
    "MongoDB",
    "Redis",
  ],
  tools: [
    "Git / GitHub",
    "Docker",
    "React Query",
    "Vercel",
    "CI/CD",
    "Axios",
  ],
};

export const projects = [
  {
    id: 1,
    slug: "vitisfera-erp-crm",
    category: "crm",
    featured: true,
    accent: "#6366f1",
    titleTr: "Vitisfera — Şirket Yönetim Sistemi",
    titleEn: "Vitisfera — Company Management System",
    categoryLabelTr: "ERP & CRM",
    categoryLabelEn: "ERP & CRM",
    descTr:
      "ERP ve CRM yeteneklerini bir arada sunan, şirket operasyonlarının uçtan uca yönetimini sağlayan kurumsal platform. Satış takibi, saha aktiviteleri, hedef ve prim hesaplamaları ile yapay zeka destekli iş zekası modülleri içerir.",
    descEn:
      "Enterprise platform combining ERP and CRM for end-to-end company operations management — sales tracking, field activities, target and commission calculations, plus AI-powered business intelligence modules.",
    techs: ["React", "TypeScript", "Tailwind CSS", "Node.js", "MongoDB", "AI"],
    github: null,
    live: null,
  },
  {
    id: 2,
    slug: "lawyer-saas",
    category: "saas",
    featured: true,
    accent: "#8b5cf6",
    titleTr: "Hukuk Bürosu Yönetim Sistemi",
    titleEn: "Law Firm Management System",
    categoryLabelTr: "SaaS Platform",
    categoryLabelEn: "SaaS Platform",
    descTr:
      "Müvekkil yönetimi, dava dosyalarının dijital arşivlenmesi ve duruşma takvimi entegrasyonu sunan sektöre özel SaaS çözümü.",
    descEn:
      "Sector-specific SaaS with client management, digital case archiving, and hearing calendar integration for law firms.",
    techs: ["React", "TypeScript", "Tailwind CSS", "REST API", ".NET"],
    github: null,
    live: null,
  },
  {
    id: 3,
    slug: "unity-survival",
    category: "game",
    featured: true,
    accent: "#10b981",
    titleTr: "Unity 2D Survival Oyunu",
    titleEn: "Unity 2D Survival Game",
    categoryLabelTr: "Oyun Geliştirme",
    categoryLabelEn: "Game Development",
    descTr:
      "Gelişmiş AI sistemleri, prosedürel dünya oluşturma ve çok oyunculu ağ altyapısı içeren performans odaklı 2D survival oyunu.",
    descEn:
      "Performance-focused 2D survival game with advanced AI, procedural world generation, and multiplayer networking.",
    techs: ["Unity", "C#", "Multiplayer", "Mobile"],
    github: null,
    live: null,
  },
  {
    id: 4,
    slug: "perfgame",
    category: "saas",
    featured: false,
    accent: "#f59e0b",
    titleTr: "PerfGame — PC Optimizasyon",
    titleEn: "PerfGame — PC Optimization",
    categoryLabelTr: "Masaüstü Uygulama",
    categoryLabelEn: "Desktop App",
    descTr:
      "Sistem performansını analiz eden ve otomatik optimizasyon uygulayan masaüstü uygulama.",
    descEn:
      "Desktop application that analyzes system performance and applies automated optimizations.",
    techs: ["C#", ".NET", "Windows API"],
    github: null,
    live: null,
  },
  {
    id: 5,
    slug: "game-web-scripts",
    category: "web",
    featured: false,
    accent: "#ef4444",
    titleTr: "Oyun Sunucu Web Platformları",
    titleEn: "Game Server Web Platforms",
    categoryLabelTr: "Web Platform",
    categoryLabelEn: "Web Platform",
    descTr:
      "Oyun sunucuları için oyuncu istatistikleri, market entegrasyonu ve yönetim paneli içeren web platformları.",
    descEn:
      "Web platforms for game servers with player statistics, marketplace integration, and admin dashboards.",
    techs: ["Node.js", "React", "MySQL", "WebSocket"],
    github: null,
    live: null,
  },
  {
    id: 6,
    slug: "ecommerce-scripts",
    category: "web",
    featured: false,
    accent: "#3b82f6",
    titleTr: "E-Ticaret Altyapıları",
    titleEn: "E-Commerce Infrastructure",
    categoryLabelTr: "E-Ticaret",
    categoryLabelEn: "E-Commerce",
    descTr:
      "İşletmelere özel, yüksek performanslı e-ticaret altyapıları ve mağaza yönetim sistemleri.",
    descEn:
      "Custom high-performance e-commerce infrastructure and store management systems for businesses.",
    techs: ["React", "Node.js", "PostgreSQL", "Stripe"],
    github: null,
    live: null,
  },
];

export const moreProjects = {
  itemsTr: [
    "Kurumsal web siteleri & landing page'ler",
    "ERP & CRM yönetim panelleri",
    "Sektöre özel SaaS çözümleri",
    "E-ticaret & ödeme entegrasyonları",
    "REST API & backend servisleri",
    "Mobil uyumlu web uygulamaları",
  ],
  itemsEn: [
    "Corporate websites & landing pages",
    "ERP & CRM admin dashboards",
    "Sector-specific SaaS solutions",
    "E-commerce & payment integrations",
    "REST APIs & backend services",
    "Mobile-responsive web applications",
  ],
};

export const experiences = [
  {
    id: 1,
    type: "work",
    startDateTr: "2026",
    startDateEn: "2026",
    endDateTr: "Devam",
    endDateEn: "Present",
    roleTr: "Kurucu & Full Stack Developer",
    roleEn: "Founder & Full Stack Developer",
    companyTr: "Revark Yazılım",
    companyEn: "Revark Yazılım",
    companyUrl: "https://revarkyazilim.com",
    locationTr: "Ankara, Türkiye",
    locationEn: "Ankara, Turkey",
    descriptionTr: [
      "Revark Yazılım'ı kurdum ve yazılım geliştirme operasyonlarını yönetiyorum.",
      "Kurumsal web uygulamaları, SaaS platformları ve ERP/CRM çözümleri geliştiriyorum.",
      "Vitisfera gibi şirket yönetim sistemleri ve sektöre özel yazılım projeleri üretiyorum.",
    ],
    descriptionEn: [
      "Founded Revark Yazılım and lead software development operations.",
      "Building enterprise web applications, SaaS platforms, and ERP/CRM solutions.",
      "Delivering company management systems like Vitisfera and sector-specific software projects.",
    ],
    techs: ["React", "Next.js", "Node.js", "TypeScript", ".NET", "PostgreSQL"],
  },
  {
    id: 2,
    type: "work",
    startDateTr: "2020",
    startDateEn: "2020",
    endDateTr: "Devam",
    endDateEn: "Present",
    roleTr: "Full Stack Developer",
    roleEn: "Full Stack Developer",
    companyTr: "Serbest & Kurumsal Projeler",
    companyEn: "Freelance & Enterprise Projects",
    locationTr: "Ankara, Türkiye · Remote",
    locationEn: "Ankara, Turkey · Remote",
    descriptionTr: [
      "6 yıldır aktif olarak full stack web uygulamaları ve SaaS çözümleri geliştiriyorum.",
      "100+ projeyi başarıyla teslim ettim — kurumsal siteler, yönetim panelleri ve e-ticaret altyapıları.",
      "Hukuk, inşaat, sağlık ve perakende gibi farklı sektörlere özel yazılım çözümleri ürettim.",
      "REST API'ler, backend servisleri ve veritabanı mimarileri tasarladım.",
    ],
    descriptionEn: [
      "Actively building full stack web applications and SaaS solutions for 6 years.",
      "Successfully delivered 100+ projects — corporate sites, admin dashboards, and e-commerce infrastructures.",
      "Built custom software solutions for law, construction, healthcare, and retail sectors.",
      "Designed REST APIs, backend services, and database architectures.",
    ],
    techs: ["React", "Next.js", "Node.js", "TypeScript", "C#", "PostgreSQL", "MongoDB"],
  },
  {
    id: 3,
    type: "education",
    startDateTr: "2025",
    startDateEn: "2025",
    endDateTr: "Devam",
    endDateEn: "Present",
    roleTr: "Önlisans — Web Tasarımı ve Kodlama",
    roleEn: "Associate's Degree — Web Design & Coding",
    companyTr: "Ankara Üniversitesi",
    companyEn: "Ankara University",
    locationTr: "Ankara, Türkiye",
    locationEn: "Ankara, Turkey",
    descriptionTr: [
      "Web teknolojileri, veritabanı yönetimi ve modern yazılım geliştirme standartları üzerine eğitim.",
    ],
    descriptionEn: [
      "Education in web technologies, database management, and modern software development standards.",
    ],
    techs: ["Web Technologies", "Database Management", "Software Engineering"],
  },
];

export const stats = [
  { value: 6, suffix: "+", keyTr: "Yıl Deneyim", keyEn: "Years Experience" },
  { value: 100, suffix: "+", keyTr: "Tamamlanan Proje", keyEn: "Projects Completed" },
  { value: 12, suffix: "+", keyTr: "Teknoloji", keyEn: "Technologies" },
  { value: 6, suffix: "+", keyTr: "Sektör", keyEn: "Industries" },
];

export const social = {
  email: "tufankiraz@revarkyazilim.com",
  phone: "+905386886241",
  phoneDisplay: "0538 688 62 41",
  github: "https://github.com/xRevenge06",
  linkedin: "https://linkedin.com/in/tufan-kiraz-920580387",
  website: "https://revarkyazilim.com",
  websiteDisplay: "revarkyazilim.com",
};
